services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '8200:15672'
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped  

